### ISSUE TITLE
book pdf not working in Text-Books directory

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/DataStructrues-Algo#4]

**Comment by ZahaanMahajan** [comment]
is this still open ?

**Comment by ArslanYM** [comment]
yes the issue is open and you can start working on it

**Comment by ZahaanMahajan** [comment]
ok on it

**Comment by ZahaanMahajan** [comment]
can we add more books related to dsa coding interview

**Comment by ArslanYM** [comment]
> can we add more books related to dsa coding interview

yes you can , clone the repo and make your changes
